server:
  error:
    include-message: always
    include-binding-errors: always

spring:
  mail:
    host: smtp.gmail.com
    port: 587
    username: vermaairline@gmail.com
    password: ndrq dsev yunk lfqh
    protocol: smtp
    properties:
      mail:
        smtp:
          auth: true
          starttls:
            enable: true
  datasource:
    password: Mypassword@12
    url: jdbc:postgresql://localhost:5432/registration
    username: postgres
  jpa:
    hibernate:
      ddl-auto: update
    properties:
      hibernate:
        dialect: org.hibernate.dialect.PostgreSQLDialect 
        format_sql: true
    show-sql: true